server:
  port: 9091
spring:
  application:
    name: consumer-feign
eureka:
  client:
    #注册中心的地址
    service-url:
      defaultZone: http://www.aaa.com:10000/eureka,http://www.bbb.com:10001/eureka,http://www.ccc.com:10002/eureka
