#注册中心的端口
server:
  port: 10001

#配置服务的名称
spring:
  application:
    name: eureka1

eureka:
  client:
    #注册中心的地址
    service-url:
      defaultZone: http://www.aaa.com:10000/eureka, http://www.ccc.com:10002/eureka
    #当前服务不能去调用其他服务 - 必须要配置
    fetch-registry: false
    #注册中心不能自我注册
    register-with-eureka: false
  #实例的主机名
  instance:
    hostname: localhost
  #关闭自我保护机制
#  server:
#    enable-self-preservation: false